
@echo "CLEARING TRASH FILES..."

del *.BAK
del *.bak
del *.TPU
del *.tpu

del SPRUCHRS\*.TPU
del SPRUCHRS\*.tpu

del SWAG\*.BAK
del SWAG\*.bak
del SWAG\*.TPU
del SWAG\*.tpu

del VB_BGI\*.BAK
del VB_BGI\*.bak
del VB_BGI\*.TPU
del VB_BGI\*.tpu

del PFORUM.RU\*.BAK
del PFORUM.RU\*.bak
del PFORUM.RU\*.TPU
del PFORUM.RU\*.tpu

del SOURS.RU\*.BAK
del SOURS.RU\*.bak
del SOURS.RU\*.TPU
del SOURS.RU\*.tpu




@echo "CLEARING FINISHED !"
